export const REGISTER_BEGIN = 'REGISTER_BEGIN';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT = 'LOGOUT';

export const UPDATEPROFILE_BEGIN = 'UPDATEPROFILE_BEGIN';
export const UPDATEPROFILE_SUCCESS = 'UPDATEPROFILE_SUCCESS';
export const UPDATEPROFILE_ERROR = 'UPDATEPROFILE_ERROR';

export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS';

export const CLEAR_ERROR = 'CLEAR_ERROR';
