export const GET_TWEETS_BEGIN = 'GET_TWEETS_BEGIN';
export const GET_TWEETS_SUCCESS = 'GET_TWEETS_SUCCESS';
export const GET_TWEETS_ERROR = 'GET_TWEETS_ERROR';

export const POST_TWEET_BEGIN = 'POST_TWEET_BEGIN';
export const POST_TWEET_SUCCESS = 'POST_TWEET_SUCCESS';
export const POST_TWEET_ERROR = 'POST_TWEET_ERROR';
